#pragma once

#include "main.h"

#define STICK_DRIVE_POWER pros::E_CONTROLLER_ANALOG_LEFT_Y
#define STICK_DRIVE_TURN pros::E_CONTROLLER_ANALOG_LEFT_X
#define STICK_ARM pros::E_CONTROLLER_ANALOG_RIGHT_Y
#define BUTTON_MOGO_MECH_CLAMP pros::E_CONTROLLER_DIGITAL_R2
#define BUTTON_MOGO_MECH_TILT pros::E_CONTROLLER_DIGITAL_R1
#define BUTTON_ARM_DOWN pros::E_CONTROLLER_DIGITAL_RIGHT
#define BUTTON_FRONT_CLAMP pros::E_CONTROLLER_DIGITAL_L2
#define BUTTON_COVER pros::E_CONTROLLER_DIGITAL_L1
#define BUTTON_RING_MECH_UP pros::E_CONTROLLER_DIGITAL_DOWN
#define BUTTON_RING_MECH_DOWN pros::E_CONTROLLER_DIGITAL_B
#define BUTTON_TOGGLE_DRIVE_BRAKE pros::E_CONTROLLER_DIGITAL_A